module.exports = {
  SERVER_PORT: 4040,

  ERROR_CODE_EMPTY: "001",
  ERROR_CODE_NOT_FOUND: "002",
  ERROR_CODE_NOT_MATCH: "003",
  ERROR_CODE_INVALID: "004",
  ERROR_CODE_TOKEN_EXPIRED: "005",
  ERROR_CODE_REFRESH_TOKEN_EXPIRED: "006",

  ERROR_CODE_UNKNOWN: "-999",

  ROLE_ADMIN: "ROLE_ADMIN",

  TOKEN_EXPIRES_TIME: "90d",
  REFRESH_TOKEN_EXPIRES_TIME: "7d"
};
